### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by mfred01** [mcdado/win-acme-dns-ovh#1]
Hi all!

I'm new in node js, but I'm quite experienced HTTP-01 validation with win-acme and in OVH DNS-01 validation with other tool than win-acme. Now I'm trying for the first time in my life OVH DNS-01 validation in win-acme and found this script.

I'm trying to implement win-acme and win-acme-dns-ovh on a brand new Windows Server 2022, with all software versions up-to-date.

I've got the following error in a simple command prompt (launching WACS.exe with all required parameters for DNS-01 validation) and also in a node.js command prompt:

----
C:\ProgramData\chocolatey\lib\win-acme\tools\win-acme-dns-ovh-master\lib\create-challenge.js:2
const parseDomain = require('parse-domain').parseDomain
                    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\ProgramData\chocolatey\lib\win-acme\tools\node_modules\parse-domain\build\main.js from C:\ProgramData\chocolatey\lib\win-acme\tools\win-acme-dns-ovh-master\lib\create-challenge.js not supported.
Instead change the require of main.js in C:\ProgramData\chocolatey\lib\win-acme\tools\win-acme-dns-ovh-master\lib\create-challenge.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (C:\ProgramData\chocolatey\lib\win-acme\tools\win-acme-dns-ovh-master\lib\create-challenge.js:2:21)
    at Object.<anonymous> (C:\ProgramData\chocolatey\lib\win-acme\tools\win-acme-dns-ovh-master\index.js:7:25) {
  code: ←[32m'ERR_REQUIRE_ESM'←[39m
}

Node.js v18.12.1
----

Thank you!

**Comment by mcdado** [comment]
Hi! Thank you for taking interest in my little project. It has always worked great for me so I'm a bit surprised that you're having problems.

First of all: how are you downloading this project and its dependencies? In my case, I always clone this repo in its own directory and after entering the directory I would run `npm install`. This pulls all the right dependencies versions. 

Alternatively, you could run `npm install win-acme-dns-ovh` in a directory and it will download everything in one step and you won't need git, only Node.js installed. Then the script file would be inside the `node_modules/win-acme-dns-ovh` sub directory.

This issue aside, you're having problems with parse-domain, which at version 5 should be compatible with both CommonJS's require system and ESM. I recently bumped the dependencies but kept that back a few versions from latest because I didn't want to switch over completely to ESM style imports. Are you forcing ESM imports? With the latest release it should work though, so make sure you're using the latest at the moment. Let me know if you manage to resolve the issue!

**Comment by mfred01** [comment]
Thank you for you prompt reply! And thank you for tips about installing the project: in my issue description, infact, I missed to say that, before that error, I had some dependency issue, too, that I solved by manually run a couple of "npm install ..." but struggled why I had to do those! Now I understand that I missed something in preparing the runtime environment...

Just another question: when you say run "npm install", I think you mean to have already installed node.js. The question is this: is there a particular runtime and/or version required by this project?
My reference of downloads is often Chocolatey.org: there I can find actually, among others, a couple of Node.js runtimes: LTS (Install) 18.12.1   and   19.1.0.      Are they both suitable for this project?

Thank you again!

PS.: if I'll understand all pieces involved in running this project, I'll have a bunch of servers to switch to win-acme + win-acme-dns-ovh...

**Comment by mcdado** [comment]
Well, this specific project uses Node.js because that's what I use. 😁

Indeed Node (together with npm that comes with it) is required to run these scripts. Of course, if your expertise is in another language, you can see what the scripts do and replicate it. 

Basically using OVH's api I'm creating TXT records with the challenges provided by win-acme. That's quite simple all things considered.

If you want to use these scripts you'll need win-acme to drive the renewals and Node.js to run the scripts.
